var webview=document.querySelector("webview");window.onresize=doLayout;
angular.module("services.webviewService",[]).value("webviewService",{hideNumbers:function(){webview.executeScript({code:"hideNumbers();"})},showNumbers:function(){try{webview.executeScript({code:"showNumbers();"})}catch(a){}},triggerLinkClick:function(a){webview.executeScript({code:"document.links["+a+"].click()"})},scrollDown:function(){webview.executeScript({code:"smoothScroll('down');"})},scrollUp:function(){webview.executeScript({code:"smoothScroll('up');"})},goBack:function(){webview.back()},
getURL:function(){return webview.src},navigateTo:function(a){webview.src=a},initializeWebview:function(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px";var c=function(){document.body.classList.remove("exited");document.body.classList.remove("crashed");document.body.classList.remove("killed")};webview.addEventListener("exit",function(a){console.log(a.type);document.body.classList.add("exited");
"abnormal"==a.type?document.body.classList.add("crashed"):"killed"==a.type&&document.body.classList.add("killed")});webview.addEventListener("loadstart",function(a){document.body.classList.add("loading");c();a.isTopLevel&&(document.querySelector("#location").value=a.url)});webview.addEventListener("loadstop",function(a){console.log("handleLoadStop")});webview.addEventListener("loadabort",function(a){console.log("oadAbort");console.log("  url: "+a.url);console.log("  isTopLevel: "+a.isTopLevel);console.log("  type: "+
a.type)});webview.addEventListener("loadredirect",function(a){c();a.isTopLevel&&(document.querySelector("#location").value=a.newUrl)});webview.addEventListener("loadcommit",function(a){console.log("committed");c();a.isTopLevel&&(console.log(a.url),document.querySelector("webview").insertCSS({file:"css/inject.css"},function(){console.log("css inserted")}),document.querySelector("webview").executeScript({file:"js/inject.js"}),document.querySelector("webview").executeScript({file:"js/scroll.js"}),doLayout())})}}).value("version",
"0.1");function doLayout(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px"}"use strict";
angular.module("services.commandService",[]).value("commandService",{getAction:function(a,c,l,k){var f=a=a.trim().toLowerCase(),e="";"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});f.startsWith("go to")&&(e=f.substr(5,f.length).trim(),f="go to",console.log(e));f.startsWith("search")&&(e=f.substr(6,f.length).trim(),f="search",console.log(e));var b={url:"",number:"",commandText:""};switch(f){case "number":b.commandText="number";b.number=
a;break;case "numbers on":case "number on":b.commandText="shownumbers";break;case "numbers off":case "numbers of":case "number off":case "number of":b.commandText="hidenumbers";break;case "scroll up":case "scott up":case "scroll of":case "grown up":case "skull":b.commandText="up";break;case "scroll down":case "school down":case "girl down":b.commandText="down";break;case "back":case "bach":case "black":case "pack":case "bike":b.commandText="back";break;case "go to":b.commandText="goto";b.url=e;break;
case "search":b.commandText="search";b.url="http://www.google.com/search?q="+e;break;case "help":b.commandText="help";break;case "nikki on":b.commandText="nikion";k="on";break;case "nikki off":case "nikki of":case "nicki off":case "nicki of":b.commandText="nikioff";break;case "noaction":b.commandText="noaction";break;default:if(isNaN(a)&&null!=c){b.commandText="unknown";a=(new Fuse(c,{keys:["text"],id:"url"})).search(a.substr(0,32));var g,d;for(d in a)if(a[d].indexOf("chrome"!=-1)){g=a[d].indexOf("/",
19);d=a[d].substring(g);g=l.match(/:\/\/(.[^/]+)/)[1]+d;break}else g=a[d];null==g&&(g=l,console.log("Did not find a fuzzy match"));b.url=g;console.log("closest matched url: "+b.url)}else b.commandText="number",b.number=a}"off"==k&&(b.commandText="noaction");return b}}).value("version","0.1");"use strict";
angular.module("services.htmlService",[]).value("htmlService",{getAllLinks:function(a){a=a.replace(/<img[^>]*>/g,"");a=$.parseHTML(a);var c=[];a=$("a",a);for(var l in a)null!=a[l]&&c.push({text:a[l].innerText,url:a[l].href});return c},getURL:function(a){-1==a.indexOf("http://")&&-1==a.indexOf("https://")&&(a="http://"+a);return a}}).value("version","0.1");"use strict";webview=document.querySelector("webview");window.onresize=doLayout;
angular.module("services.webviewService",[]).value("webviewService",{hideNumbers:function(){webview.executeScript({code:"hideNumbers();"})},showNumbers:function(){try{webview.executeScript({code:"showNumbers();"})}catch(a){}},triggerLinkClick:function(a){webview.executeScript({code:"document.links["+a+"].click()"})},scrollDown:function(){webview.executeScript({code:"smoothScroll('down');"})},scrollUp:function(){webview.executeScript({code:"smoothScroll('up');"})},goBack:function(){webview.back()},
getURL:function(){return webview.src},navigateTo:function(a){webview.src=a},initializeWebview:function(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px";var c=function(){document.body.classList.remove("exited");document.body.classList.remove("crashed");document.body.classList.remove("killed")};webview.addEventListener("exit",function(a){console.log(a.type);document.body.classList.add("exited");
"abnormal"==a.type?document.body.classList.add("crashed"):"killed"==a.type&&document.body.classList.add("killed")});webview.addEventListener("loadstart",function(a){document.body.classList.add("loading");c();a.isTopLevel&&(document.querySelector("#location").value=a.url)});webview.addEventListener("loadstop",function(a){console.log("handleLoadStop")});webview.addEventListener("loadabort",function(a){console.log("oadAbort");console.log("  url: "+a.url);console.log("  isTopLevel: "+a.isTopLevel);console.log("  type: "+
a.type)});webview.addEventListener("loadredirect",function(a){c();a.isTopLevel&&(document.querySelector("#location").value=a.newUrl)});webview.addEventListener("loadcommit",function(a){console.log("committed");c();a.isTopLevel&&(console.log(a.url),document.querySelector("webview").insertCSS({file:"css/inject.css"},function(){console.log("css inserted")}),document.querySelector("webview").executeScript({file:"js/inject.js"}),document.querySelector("webview").executeScript({file:"js/scroll.js"}),doLayout())})}}).value("version",
"0.1");function doLayout(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px"}"use strict";
angular.module("controllers.voiceController",[]).controller("voiceController",["$scope","$http","$timeout","htmlService","commandService","webviewService",function(a,c,l,k,f,e){a.go=function(){a.showStartScreen=!1;var b=k.getURL(a.url);a.url=b;e.navigateTo(b);c.get(b).then(function(b){a.pageLinks=k.getAllLinks(b.data)})};a.showStartScreen=function(){a.showStartScreen=!0;console.log("showing startup screen")};a.init=function(){a.showStartScreen=!0;a.micStatus="off";a.numbersStatus="on";a.niki="on";
a.microphoneurl="css/images/microphone.gif";console.log("init function");a.speechInput="Listening...";setInterval(function(){var b=document.querySelector("#location").value;b!=a.url&&(console.log("page links should be updated now"),c.get(b).then(function(e){a.pageLinks=k.getAllLinks(e.data);a.url=b}))},1E3);e.initializeWebview();var b=function(){e.showNumbers()},g=null;a.show=function(){console.log("show function");e.showNumbers();g=setInterval(b,1E3)};var d=new webkitSpeechRecognition;d.continuous=
!0;d.interimResults=!0;d.start();d.onstart=function(){a.$apply(function(){a.micStatus="on"});console.log("starting webkitSpeechRecognition: "+(new Date).toString("yyyy-MM-dd"))};d.onerror=function(b){"no-speech"==b.error&&(a.$apply(function(){a.micStatus="off";a.speechInput="Listening..."}),console.log("error - no speech"));"audio-capture"==b.error&&(a.$apply(function(){a.micStatus="off";a.speechInput="Check microphone"}),console.log("error - audio-capture"));"not-allowed"==b.error&&(a.$apply(function(){a.micStatus=
"off";a.speechInput="Check microphone"}),console.log("error - audio-capture"))};d.onend=function(){console.log("end webkitSpeechRecognition: "+(new Date(event.timeStamp)).toString("yyyy-MM-dd"));d.start()};d.onresult=function(c){for(var d=c.resultIndex;d<c.results.length;++d)if(c.results[d].isFinal){a.$apply(function(){a.speechInput=c.results[d][0].transcript});console.log(c.results[d][0].transcript);var h=f.getAction(c.results[d][0].transcript,a.pageLinks,a.url,a.niki);switch(h.commandText){case "number":e.triggerLinkClick(h.number);
break;case "unknown":h.url=k.getURL(h.url);e.navigateTo(h.url);break;case "shownumbers":e.showNumbers();g=setInterval(b,1E3);a.$apply(function(){a.numbersStatus="on"});break;case "hidenumbers":clearInterval(g);e.hideNumbers();a.$apply(function(){a.numbersStatus="off"});break;case "down":e.scrollDown();break;case "back":e.goBack();break;case "up":e.scrollUp();break;case "goto":h.url=k.getURL(h.url);e.navigateTo(h.url);a.$apply(function(){a.showStartScreen=!1});break;case "search":e.navigateTo(h.url);
a.$apply(function(){a.showStartScreen=!1});break;case "help":a.$apply(function(){a.showStartScreen=!0});break;case "nikion":a.$apply(function(){a.niki="on"});break;case "nikioff":a.$apply(function(){a.niki="off"})}console.log(h)}else a.$apply(function(){a.speechInput=c.results[d][0].transcript}),console.log(c.results[d][0].transcript)}};a.init();a.show()}]);