angular.module("services.commandService",[]).value("commandService",{getAction:function(a,d,f,l){var g=a=a.trim().toLowerCase(),c="";"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});g.startsWith("go to")&&(c=g.substr(5,g.length).trim(),g="go to",console.log(c));g.startsWith("search")&&(c=g.substr(6,g.length).trim(),g="search",console.log(c));var b={url:"",number:"",commandText:""};switch(g){case "number":b.commandText="number";b.number=
a;break;case "numbers on":case "number on":b.commandText="shownumbers";break;case "numbers off":case "numbers of":case "number off":case "number of":b.commandText="hidenumbers";break;case "scroll up":case "scott up":case "scroll of":case "grown up":case "grow up":case "skull":b.commandText="up";break;case "scroll down":case "school down":case "girl down":b.commandText="down";break;case "back":case "bach":case "black":case "pack":case "bike":b.commandText="back";break;case "go to":b.commandText="goto";
b.url=c;break;case "search":b.commandText="search";b.url="http://www.google.com/search?q="+c;break;case "help":b.commandText="help";break;case "nikki on":b.commandText="nikion";l="on";break;case "nikki off":case "nikki of":case "nicki off":case "nicki of":b.commandText="nikioff";break;case "noaction":b.commandText="noaction";break;default:if(isNaN(a)&&null!=d){b.commandText="unknown";a=(new Fuse(d,{keys:["text"],id:"url"})).search(a.substr(0,32));var h,m;for(m in a)if(a[m].indexOf("chrome"!=-1)){h=
a[m].indexOf("/",19);m=a[m].substring(h);h=f.match(/:\/\/(.[^/]+)/)[1]+m;break}else h=a[m];null==h&&(h=f,console.log("Did not find a fuzzy match"));b.url=h;console.log("closest matched url: "+b.url)}else b.commandText="number",b.number=a}"off"==l&&(b.commandText="noaction");return b}}).value("version","0.1");"use strict";
angular.module("services.htmlService",[]).value("htmlService",{getAllLinks:function(a){a=a.replace(/<img[^>]*>/g,"");a=$.parseHTML(a);var d=[];a=$("a",a);for(var f in a)null!=a[f]&&d.push({text:a[f].innerText,url:a[f].href});return d},getURL:function(a){-1==a.indexOf("http://")&&-1==a.indexOf("https://")&&(a="http://"+a);return a}}).value("version","0.1");"use strict";var webview=document.querySelector("webview");window.onresize=doLayout;
angular.module("services.webviewService",[]).value("webviewService",{hideNumbers:function(){webview.executeScript({code:"hideNumbers();"})},showNumbers:function(){try{webview.executeScript({code:"showNumbers();"})}catch(a){}},triggerLinkClick:function(a){webview.executeScript({code:"document.links["+a+"].click()"})},scrollDown:function(){webview.executeScript({code:"smoothScroll('down');"})},scrollUp:function(){webview.executeScript({code:"smoothScroll('up');"})},goBack:function(){webview.back()},
getURL:function(){return webview.src},navigateTo:function(a){webview.src=a},initializeWebview:function(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px";var d=function(){document.body.classList.remove("exited");document.body.classList.remove("crashed");document.body.classList.remove("killed")};webview.addEventListener("exit",function(a){console.log(a.type);document.body.classList.add("exited");
"abnormal"==a.type?document.body.classList.add("crashed"):"killed"==a.type&&document.body.classList.add("killed")});webview.addEventListener("loadstart",function(a){document.body.classList.add("loading");d();a.isTopLevel&&(document.querySelector("#location").value=a.url)});webview.addEventListener("loadstop",function(a){console.log("handleLoadStop")});webview.addEventListener("loadabort",function(a){console.log("oadAbort");console.log("  url: "+a.url);console.log("  isTopLevel: "+a.isTopLevel);console.log("  type: "+
a.type)});webview.addEventListener("loadredirect",function(a){d();a.isTopLevel&&(document.querySelector("#location").value=a.newUrl)});webview.addEventListener("loadcommit",function(a){console.log("committed");d();a.isTopLevel&&(console.log(a.url),document.querySelector("webview").insertCSS({file:"css/inject.css"},function(){console.log("css inserted")}),document.querySelector("webview").executeScript({file:"js/inject.js"}),document.querySelector("webview").executeScript({file:"js/scroll.js"}),doLayout())})}}).value("version",
"0.1");function doLayout(){var a=document.querySelector("#controls").offsetHeight,a=document.documentElement.clientHeight-a;webview.style.width=document.documentElement.clientWidth+"px";webview.style.height=a+"px"}"use strict";
angular.module("controllers.voiceController",[]).controller("voiceController",["$scope","$http","$timeout","htmlService","commandService","webviewService",function(a,d,f,l,g,c){var b=analytics.getService("niki");b.getConfig().addCallback(function(b){b.setTrackingPermitted(a.analytics)});var h=b.getTracker("UA-45746229-1");a.analyticsChanged=function(){console.log("changed: "+a.analytics);b.getConfig().addCallback(function(b){b.setTrackingPermitted(a.analytics)})};a.go=function(){a.showStartScreen=
!1;var b=l.getURL(a.url);a.url=b;c.navigateTo(b);d.get(b).then(function(b){a.pageLinks=l.getAllLinks(b.data)});h.sendEvent("ui_action","formsubmit","go")};a.showStartScreen=function(){a.showStartScreen=!0;console.log("showing startup screen")};a.init=function(){a.showStartScreen=!0;a.micStatus="off";a.numbersStatus="on";a.niki="on";a.analytics=!0;a.microphoneurl="css/images/microphone.gif";console.log("init function");a.speechInput="Listening...";setInterval(function(){var b=document.querySelector("#location").value;
b!=a.url&&(console.log("page links should be updated now"),d.get(b).then(function(c){a.pageLinks=l.getAllLinks(c.data);a.url=b}))},1E3);c.initializeWebview();var b=function(){c.showNumbers()},f=null;a.show=function(){console.log("show function");c.showNumbers();f=setInterval(b,1E3)};var e=new webkitSpeechRecognition;e.continuous=!0;e.interimResults=!0;e.start();e.onstart=function(){a.$apply(function(){a.micStatus="on"});console.log("starting webkitSpeechRecognition: "+(new Date).toString("yyyy-MM-dd"))};
e.onerror=function(b){"no-speech"==b.error&&(a.$apply(function(){a.micStatus="off";a.speechInput="Listening..."}),console.log("error - no speech"));"audio-capture"==b.error&&(a.$apply(function(){a.micStatus="off";a.speechInput="Check microphone"}),console.log("error - audio-capture"));"not-allowed"==b.error&&(a.$apply(function(){a.micStatus="off";a.speechInput="Check microphone"}),console.log("error - audio-capture"))};e.onend=function(){console.log("end webkitSpeechRecognition: "+(new Date(event.timeStamp)).toString("yyyy-MM-dd"));
e.start()};e.onresult=function(d){for(var e=d.resultIndex;e<d.results.length;++e)if(d.results[e].isFinal){a.$apply(function(){a.speechInput=d.results[e][0].transcript});console.log(d.results[e][0].transcript);var k=g.getAction(d.results[e][0].transcript,a.pageLinks,a.url,a.niki);switch(k.commandText){case "number":c.triggerLinkClick(k.number);break;case "unknown":k.url=l.getURL(k.url);c.navigateTo(k.url);break;case "shownumbers":c.showNumbers();f=setInterval(b,1E3);a.$apply(function(){a.numbersStatus=
"on"});break;case "hidenumbers":clearInterval(f);c.hideNumbers();a.$apply(function(){a.numbersStatus="off"});break;case "down":c.scrollDown();break;case "back":c.goBack();break;case "up":c.scrollUp();break;case "goto":k.url=l.getURL(k.url);c.navigateTo(k.url);a.$apply(function(){a.showStartScreen=!1});h.sendEvent("ui_action","voice","goto");break;case "search":c.navigateTo(k.url);a.$apply(function(){a.showStartScreen=!1});h.sendEvent("ui_action","voice","search");break;case "help":a.$apply(function(){a.showStartScreen=
!0});break;case "nikion":a.$apply(function(){a.niki="on"});break;case "nikioff":a.$apply(function(){a.niki="off"})}console.log(k)}else a.$apply(function(){a.speechInput=d.results[e][0].transcript}),console.log(d.results[e][0].transcript)}};a.init();a.show()}]);